### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by glyg** [centuri-engineering/clicket#4]
- [x] add referee
- [x] set default procedure stage to N/A
- [x] set default request type to consulting
- [x] split domain / status
- [x] solve bug in ticket list

**Comment by glyg** [comment]
Looks like it keeps last entry (users did not complain)
